_wandb:
    value:
        cli_version: 0.17.5
        m: []
        python_version: 3.9.7
        t:
            "1":
                - 12
                - 53
                - 55
            "2":
                - 12
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.7
            "5": 0.17.5
            "8":
                - 5
            "12": 0.17.5
            "13": darwin-arm64
L_p regularization:
    value: L_2
dataset:
    value: Student_Performance.csv
dropout:
    value: 0.1
epochs:
    value: 10000
lambda:
    value: 0.01
learning_rate:
    value: 0.005
max_patience:
    value: 100
model:
    value: Multiple Linear Regression
